import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import 'leaflet/dist/leaflet.css';
import './globals.css';
import Header from '@/components/Header';
import ClientProviders from '@/components/client-provider';
import { Toaster } from 'sonner';

const raleway = Raleway({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased`}>
        <ClientProviders>
          <Header />
          {children}
        </ClientProviders>
        <Toaster />
      </body>
    </html>
  );
}
